// All image URLs used across the site.
// Personal portraits/screenshots: customer-assets (uploaded by user)
// Premium editorial backdrops & textures: generated by design agent

export const ASSETS = {
  // Uploaded personal photos & social proof screenshots
  portrait: "https://customer-assets.emergentagent.com/job_642d8b52-b80f-44cc-acab-581dd919f996/artifacts/mewg9mch_IMG_3803.jpg", // hero portrait (lavender dress)
  igScreenshot: "https://customer-assets.emergentagent.com/job_642d8b52-b80f-44cc-acab-581dd919f996/artifacts/ifisjrqw_IMG_3802.jpg",
  tiktokScreenshot: "https://customer-assets.emergentagent.com/job_642d8b52-b80f-44cc-acab-581dd919f996/artifacts/a8t0bfde_IMG_3804.jpg",
  youtubeScreenshot: "https://customer-assets.emergentagent.com/job_642d8b52-b80f-44cc-acab-581dd919f996/artifacts/vv04013n_IMG_3805.jpg",
  kickScreenshot: "https://customer-assets.emergentagent.com/job_642d8b52-b80f-44cc-acab-581dd919f996/artifacts/ek7qu2y5_IMG_3806.PNG",

  // Design-agent generated luxury textures / editorial backdrops
  liquidGold: "https://static.prod-images.emergentagent.com/jobs/642d8b52-b80f-44cc-acab-581dd919f996/images/4ba77ad01ebb05d2777c3017f2b02b41c494ab3f5d93f8426420f05a912655b7.png",
  beautyMacro: "https://static.prod-images.emergentagent.com/jobs/642d8b52-b80f-44cc-acab-581dd919f996/images/e830639acdb6c7bde215947c39f369e829d9643731ff89907e16e2b210a7fa51.png",
  laSunset: "https://static.prod-images.emergentagent.com/jobs/642d8b52-b80f-44cc-acab-581dd919f996/images/2573a92fb03360efef5e1f33b5e313a9dfded538a2195ebcf7a6990a59964b2f.png",
  fashionStudio: "https://static.prod-images.emergentagent.com/jobs/642d8b52-b80f-44cc-acab-581dd919f996/images/678683bc257c996ccbc61fd8235ffd3c3b5a0a20f1d8d6a739938256bf53038f.png",
  kickFrostedGreen: "https://static.prod-images.emergentagent.com/jobs/642d8b52-b80f-44cc-acab-581dd919f996/images/a7d2b5bb53d4226379884ac2db701e530b89dd122c57c6376815c2ae329d09f6.png",

  // Premium stock — luxury fashion / lifestyle (Unsplash, curated soft luxury)
  fashionEditorial: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=1400",
  beautyClose: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=1400",
  travelLuxury: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=1400",
  livestream: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&q=80&w=1400",
  youthCulture: "https://images.unsplash.com/photo-1517462964-21fdcec3f25b?auto=format&fit=crop&q=80&w=1400",
  viralTrend: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=1400",
  entertainment: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1400",
  lifestyleSoft: "https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?auto=format&fit=crop&q=80&w=1400",
  champagne: "https://images.unsplash.com/photo-1604079628040-94301bb21b91?auto=format&fit=crop&q=80&w=1400",
  blushAbstract: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=1400",
};

export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/yarenalaca",
  tiktok: "https://www.tiktok.com/@yarenalaca",
  youtube: "https://www.youtube.com/@YarenAlaca",
  kick: "https://kick.com/yarenalaca",
  email: "mailto:info@yarenalacapr.com",
};
